### ISSUE TITLE
UX: stringify integers in pod environment settings

### ISSUE THREAD

**Issue by Supermathie** [mpalmer/moby-derp#5]
I can certainly see the reason for not stringifying e.g. Boolean values (doing so could easily lead to subtle bugs) but I can't really think of an argument for not doing so for Integers/Floats:

e.g.:
```
michael:~/moby-derp$ bundle exec moby-derp minecraft.yml
There was an error reading the pod config file minecraft.yml: {"EULA"=>"TRUE", "TZ"=>"America/Toronto", "VERSION"=>"1.12.2", "PORT"=>25570} contains non-string value(s): [25570]
```

**Comment by mpalmer** [comment]
Floats can be truncated / modified, so they're also in the "doing so could easily lead to subtle bugs" camp.  But the primary reason is consistency.  Once word gets around that a programmer has gone soft, YAML stops respecting you, and then it's nothing but `to_s`, `to_s`, `to_s`!

I just noticed that I didn't make it explicit that env var values had to be strings, so I've [fixed that](https://github.com/mpalmer/moby-derp/commit/fe8bb3425b1bf71821d9efa316dd083f154a0533) in `example.yml`, along with a couple of trivial examples to get the point across.  While it doesn't necessarily make life easier for you, at least it might stop people second-guessing themselves about why it's not working.

**Comment by Supermathie** [comment]
Sounds like an entirely sensible approach.
